### ISSUE TITLE
[BUG] Outputs to wrong sys.stdout when default arguments are used

### ISSUE THREAD

**Issue by sehoffmann** [sjmikler/progress-table#15]
## Problem

If one replaces `sys.stdout` with a custom stream, *progress-table* does still output to the old stream (usually standard out), even if the table is created and initialized **AFTER** the stream has been replaced.

The reason for this is the default argument [file=sys.stdout,](https://github.com/sjmikler/progress-table/blob/db2ff43a1792e4d0eeb9bc8f2fef0f0ac5434826/progress_table/v1/progress_table.py#L148) that gets evaluated when the module is imported for the first time and **NOT** when an actual table object is created. This can be hard to spot!

## Suggested Solution
Replace the default argument with `file=None` and set it to `sys.stdout` in the constructor. This delays the evaluation of `sys.stdout` to the time at which a table object is actually created.

**Even better:** Officially accept `None` values for `file` as part of the interface and, in that case, retrieve `sys.stdout` on each write/flush instead of on object creation. This would allow one to redirect the output of progress-table even long after a table object has been created. The old behavior, i.e. sticking to a single, specific stream for all eternity, can still be achieved by explicitly passing `file=sys.stdout` to the constructor.

**Comment by szmikler** [comment]
Nice catch! I like the "Even better" solution. This should be fixed with this PR: #16

**Comment by sehoffmann** [comment]
Wow, thanks for the super quick fix :+1:

**Comment by szmikler** [comment]
Merged in 1.2.2.
