### ISSUE TITLE
[BUG] pip install seemingly not working

### ISSUE THREAD

**Issue by jacopogiuliani** [sjmikler/progress-table#17]
Hello. Thank you for your amazing work. Looks really interesting and I really would like to implement it in my pytorch training loop.
However, when installing using pip and trying your proposed example, the import fails with error:

File "/usr/local/lib/python3.10/site-packages/progress_table/__init__.py", line 3, in <module>
    from progress_table.v0.progress_table import ProgressTableV0
ModuleNotFoundError: No module named 'progress_table.v0'

I'm working in a conda environment with python 3.10.
Maybe there's some issue with the Pypi installer? Thank you for any help you could give me.

**Comment by szmikler** [comment]
Taking a look

**Comment by szmikler** [comment]
Thanks for reporting this, I will add tests to prevent this happening in the future. This should be fixed in version 1.2.3. Let me know if it works for you now.

**Comment by jacopogiuliani** [comment]
Thank you very much. You were super fast and efficient! everything works now.
