### ISSUE TITLE
Add borders between rows?

### ISSUE THREAD

**Issue by hungcs** [sjmikler/progress-table#3]
Would it be possible to add borders between rows? The table becomes hard to read with a lot of data between epochs. I tried looking into the style argument, but that seems to mostly govern coloring

<img width="840" alt="Screen Shot 2023-09-29 at 5 06 40 PM" src="https://github.com/sjmikler/progress-table/assets/85463385/8e07545d-96d4-4c64-8a32-2617157d39eb">

**Comment by szmikler** [comment]
Hey! Sorry for the late replay. 

Borders between rows are implemented. Try out setting split=True when calling `next_row`.

For example:
```
table.next_row(split=True)
```
