### ISSUE TITLE
[BUG] Columns don't align correctly when emojis are used

### ISSUE THREAD

**Issue by naddeoa** [sjmikler/progress-table#5]
![image](https://github.com/sjmikler/progress-table/assets/1233709/6669520c-69b5-4d84-9203-b492efde2252)

Seems like something about emoji's causes the column width to overflow. I assume emoji's are secretly more than a single character wide.

**Comment by szmikler** [comment]
Seems like the emojis and other unicode symbols can have width of just half of a character. This makes it difficult to manage, especially in dynamic cases like progress bars. I won't be working on this anytime soon.

**Comment by szmikler** [comment]
This is partially solved in `rich.table`. Attaching images from two different terminals (both using rich):

![obraz](https://github.com/sjmikler/progress-table/assets/43541355/f9d8114f-e0ba-4e28-82eb-3f662140775a)
![obraz](https://github.com/sjmikler/progress-table/assets/43541355/4d0b8c7d-c0e0-4374-923a-6f160f6b215f)

I will look into how it is handled in rich and possibly add a similar solution that would cover at least some of the terminals.
