### ISSUE TITLE
[FEATURE] Continuous progress bar

### ISSUE THREAD

**Issue by naddeoa** [sjmikler/progress-table#7]
For my table, I don't actually know when the items will finish. They shell out to a subprocess where anything can happen. Having a spinner/bouncing option would be nice there so highlight that things are happening but the end isn't known. I think I'd have to manually fake this by just making it fill up slowly and then rush to 100% when the subprocess finishes without this feature.

**Comment by szmikler** [comment]
This feature was added in 1.0.0 version. Whenever length of the iterable is unknown, the progress bar will be incremented at every step. Whenever it fills ups, it will reset and start over.
