### ISSUE TITLE
[FEATURE] Pandas as an optional dependency

### ISSUE THREAD

**Issue by naddeoa** [sjmikler/progress-table#8]
It looks like pandas is only being used to export data from the table. It's a rather large dependency for a feature that I don't plan on using. Any opposition to making it an optional dependency and surrounding the import with an exception error message that tells you to install pandas if you want to export the table in pandas format?

**Comment by szmikler** [comment]
Starting at 1.0.0, both Pandas and Numpy are optional dependencies. Whenever someone attempts to use `to_numpy` or `to_df` without appropriate library, an exception is raised.
