### ISSUE TITLE
[FEATURE] Nested/multi level progress

### ISSUE THREAD

**Issue by naddeoa** [sjmikler/progress-table#9]
This is a handy feature in tqdm and it works well for a row based table UX like `progress-table` has. I'd like to use it to show both the overall progress of the table (since the user doesn't know how many rows are to come) as well as the progress for the current row.

**Comment by szmikler** [comment]
This feature was added in version 1.1.0.

First progress bar can be either "embedded" or "non-embedded", depending on your settings. All the nested progress bars will be standard. Moreover, "non-embedded" progress bar is not obscuring the latest row anymore, they are printed "below" the table.

![obraz](https://github.com/sjmikler/progress-table/assets/43541355/729ac653-af7b-49a3-b5cb-9e3570e71111)
